-- Create a table for public profiles
create table bookmarks (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  title text not null,
  url text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Set up Row Level Security (RLS)
-- See https://supabase.com/docs/guides/auth/row-level-security for more details.
alter table bookmarks enable row level security;

create policy "Individuals can create bookmarks." on bookmarks for
    insert with check (auth.uid() = user_id);

create policy "Individuals can view their own bookmarks. " on bookmarks for
    select using (auth.uid() = user_id);

create policy "Individuals can update their own bookmarks." on bookmarks for
    update using (auth.uid() = user_id);

create policy "Individuals can delete their own bookmarks." on bookmarks for
    delete using (auth.uid() = user_id);

-- Enable realtime for this table
alter publication supabase_realtime add table bookmarks;
